brew 'autoconf'
brew 'bash'
brew 'bash-completion'
brew 'cmake'
brew 'curl', args: ['with-libressl']
brew 'direnv', args: ['HEAD']
brew 'doxygen'
brew 'fasd'
brew 'fish', args: ['HEAD']
brew 'fzf', args: ['HEAD']
brew 'gdbm'
brew 'gettext'
brew 'gist'
brew 'git'
brew 'git-secrets'
brew 'gmp'
brew 'gnupg2'
brew 'go'
brew 'godep'
brew 'gpg-agent'
brew 'grc', args: ['HEAD']
brew 'brew-cask-completion'
brew 'hub'
brew 'joe'
brew 'keybase'
brew 'keychain'
brew 'ldns'
brew 'libassuan'
brew 'libffi'
brew 'libgcrypt'
brew 'libgpg-error'
brew 'libksba'
brew 'libpng'
brew 'libressl'
brew 'libsodium'
brew 'libxml2'
brew 'libyaml'
brew 'mas'
brew 'mercurial'
brew 'nmap'
brew 'node'
brew 'openssl'
brew 'pandoc'
brew 'pcre2'
brew 'pinentry'
brew 'pkg-config'
brew 'pth'
brew 'pyenv', args: ['HEAD']
brew 'readline'
brew 'ruby-install', args: ['HEAD']
brew 'ry', args: ['HEAD']
brew 'shellcheck'
brew 'sqlite'
brew 'syncthing'
brew 'syncthing-inotify'
brew 'tarsnap', args: ['with-xz']
brew 'terminal-notifier'
brew 'the_platinum_searcher', args: ['HEAD']
brew 'thefuck'
brew 'trash'
brew 'ttyrec'
brew 'unrar'
brew 'vcprompt', args: ['HEAD']
brew 'xz'
cask '0xed'
cask '1password-beta'
cask 'alfred'
cask 'atom-beta'
cask 'avira-antivirus'
cask 'blockblock'
cask 'cyberduck'
cask 'etrecheck'
cask 'exa'
cask 'firefoxnightly'
cask 'flux'
cask 'font-liberation-mono-for-powerline'
cask 'font-mononoki'
cask 'imagealpha'
cask 'imageoptim'
cask 'insomniax'
cask 'iterm2-nightly'
cask 'keka'
cask 'noejectdelay'
cask 'prey'
cask 'slack'
cask 'sublime-text3'
cask 'telegram'
cask 'timemachinescheduler'
cask 'trash-it'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox', restart_service: :changed
cask 'vlc-nightly'
cask 'xld'
cask_args appdir: '/Applications'
mas 'Install OS X El Capitan', id: 1018109117
mas 'Keynote', id: 409183694
mas 'Loadables', id: 436748346
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Remote Desktop', id: 409907375
mas 'TrashMe', id: 443126292
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'domt4/chromium'
tap 'homebrew/binary'
tap 'homebrew/bundle'
tap 'homebrew/command-not-found'
tap 'homebrew/completions'
tap 'homebrew/dupes'
tap 'homebrew/fuse'
tap 'homebrew/gui'
tap 'homebrew/head-only'
tap 'homebrew/python'
tap 'homebrew/science'
tap 'homebrew/services'
tap 'homebrew/versions'
