
# tap repositories and their packages

tap caskroom/cask
cask 0xed
cask alfred
cask avira-antivirus
cask blockblock
cask cyberduck
cask etrecheck
cask exa
cask flux
cask imagealpha
cask imageoptim
cask insomniax
cask keka
cask noejectdelay
cask prey
cask qsyncthingtray
cask slack
cask telegram
cask timemachinescheduler
cask trash-it
cask vagrant-manager
cask vagrant
cask virtualbox
cask xld

tap caskroom/fonts
cask font-liberation-mono-for-powerline

tap caskroom/versions
cask 1password-beta
cask atom-beta
cask firefoxnightly
cask iterm2-nightly
cask sublime-text3
cask vlc-nightly

tap domt4/chromium

tap homebrew/binary

tap homebrew/bundle

tap homebrew/command-not-found

tap homebrew/completions
brew brew-cask-completion

tap homebrew/core
brew autoconf
brew bash
brew ccache
brew cmake
brew curl
brew direnv --HEAD
brew fasd
brew fish --HEAD
brew fzf --HEAD
brew gettext
brew gist
brew git
brew gnupg2 --without-libusb-compat --without-dirmngr
brew go
brew hub
brew joe
brew keybase
brew keychain
brew ldns
brew libassuan
brew libffi
brew libgcrypt
brew libksba
brew libpng
brew libressl
brew libsodium
brew libxml2
brew libyaml
brew mas
brew nmap
brew node
brew pcre2
brew pinentry
brew pth
brew readline
brew ruby-install --HEAD
brew shellcheck --HEAD
brew syncthing-inotify --HEAD
brew syncthing
brew tarsnap --with-xz
brew terminal-notifier
brew the_platinum_searcher
brew thefuck
brew trash
brew unrar
brew python
brew xz

tap homebrew/dupes
brew unzip

tap homebrew/fuse

tap homebrew/gui

tap homebrew/head-only

tap homebrew/python

tap homebrew/science

tap homebrew/services

tap homebrew/versions

tap peco/peco

tap rcmdnk/file
brew brew-file

tap telemachus/desc
