
# tap repositories and their packages

tap caskroom/cask
cask 0xed
cask alfred
cask avira-antivirus
cask blockblock
cask cyberduck
cask etrecheck
cask exa
cask flux
cask imagealpha
cask imageoptim
cask insomniax
cask keka
cask noejectdelay
cask prey
cask qsyncthingtray
cask slack
cask telegram
cask timemachinescheduler
cask trash-it
cask vagrant-manager
cask vagrant
cask virtualbox
cask xld

tap caskroom/fonts
cask font-liberation-mono-for-powerline

tap caskroom/versions
cask 1password-beta
cask atom-beta
cask firefoxnightly
cask iterm2-nightly
cask sublime-text3
cask vlc-nightly

tap domt4/chromium

tap homebrew/binary

tap homebrew/bundle

tap homebrew/command-not-found

tap homebrew/completions
brew brew-cask-completion

tap homebrew/core
brew autoconf
brew bash
brew cabal-install
brew ccache
brew cmake
brew curl
brew direnv --HEAD
brew doxygen
brew fasd
brew fish --HEAD
brew fzf --HEAD
brew gdbm
brew gettext
brew ghc
brew gist
brew git-secrets
brew git
brew gmp
brew gnupg2 --without-libusb-compat --without-dirmngr --with-readline
brew go
brew gpg-agent
brew hub
brew joe
brew keybase
brew keychain
brew ldns
brew libassuan
brew libffi
brew libgcrypt
brew libgpg-error
brew libksba
brew libpng
brew libressl
brew libsodium
brew libxml2
brew libyaml
brew mas
brew mercurial
brew nmap
brew node
brew openssl
brew pandoc
brew pcre2
brew pinentry
brew pkg-config
brew pth
brew pyenv-virtualenv
brew pyenv
brew python --without-sqlite
brew readline
brew ruby-install --HEAD
brew shellcheck --HEAD
brew syncthing-inotify --HEAD
brew syncthing --HEAD
brew tarsnap --with-xz
brew terminal-notifier
brew the_platinum_searcher
brew thefuck
brew trash
brew unrar
brew xz

tap homebrew/dupes
brew unzip

tap homebrew/fuse

tap homebrew/gui

tap homebrew/head-only

tap homebrew/python

tap homebrew/science

tap homebrew/services

tap homebrew/versions

tap peco/peco

tap rcmdnk/file
brew brew-file

tap telemachus/desc

# App Store applications
appstore 1018109117 Install OS X El Capitan
appstore 409183694 Keynote
appstore 436748346 Loadables
appstore 409203825 Numbers
appstore 409201541 Pages
appstore 409907375 Remote Desktop
appstore 748816884 Steuererklärung
appstore 443126292 TrashMe
